import type {
  AthleteSummary,
  CompletedSession,
  Exercise,
  Program,
  ProgramTemplate,
  ScheduledWorkout,
  WorkspaceData,
} from "./domain";

export const globalExercises: Exercise[] = [
  {
    id: "back-squat",
    name: "Back squat",
    category: "Strength",
    cue: "Brace, sit between the hips, drive evenly.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "load", "rpe"],
  },
  {
    id: "bench-press",
    name: "Bench press",
    category: "Strength",
    cue: "Set the upper back and keep the feet planted.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "load", "rpe"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian deadlift",
    category: "Strength",
    cue: "Push the hips back and keep the bar close.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "load", "rpe"],
  },
  {
    id: "push-up",
    name: "Push-up",
    category: "Bodyweight",
    cue: "Move as one line and finish with long arms.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "rpe"],
  },
  {
    id: "pull-up",
    name: "Pull-up",
    category: "Bodyweight",
    cue: "Start long, pull the chest toward the bar.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "rpe"],
  },
  {
    id: "zone-2-bike",
    name: "Zone 2 bike",
    category: "Cardio",
    cue: "Keep a sustainable conversational pace.",
    scope: "global",
    defaultMode: "result",
    defaultFields: ["duration", "distance", "rpe"],
  },
  {
    id: "easy-run",
    name: "Easy run",
    category: "Cardio",
    cue: "Relaxed pace; finish feeling like you could continue.",
    scope: "global",
    defaultMode: "result",
    defaultFields: ["duration", "distance", "rpe"],
  },
  {
    id: "rowing-intervals",
    name: "Rowing intervals",
    category: "Conditioning",
    cue: "Repeatable effort across every interval.",
    scope: "global",
    defaultMode: "intervals",
    defaultFields: ["rounds", "duration", "distance", "rpe"],
  },
  {
    id: "plank",
    name: "Plank",
    category: "Core",
    cue: "Ribs down, glutes tight, breathe behind the brace.",
    scope: "global",
    defaultMode: "result",
    defaultFields: ["duration", "rpe"],
  },
  {
    id: "mobility-flow",
    name: "Full-body mobility flow",
    category: "Mobility",
    cue: "Move slowly through a comfortable range.",
    scope: "global",
    defaultMode: "none",
    defaultFields: [],
  },
  {
    id: "snatch",
    name: "Snatch",
    category: "Weightlifting",
    cue: "Stay balanced through the pull and receive actively.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "load", "rpe"],
  },
  {
    id: "clean-jerk",
    name: "Clean & jerk",
    category: "Weightlifting",
    cue: "Finish the pull, meet the bar, then drive vertically.",
    scope: "global",
    defaultMode: "sets",
    defaultFields: ["reps", "load", "rpe"],
  },
];

export const initialPersonalExercises: Exercise[] = [
  {
    id: "tempo-goblet-squat",
    name: "Tempo goblet squat",
    category: "General",
    cue: "3 seconds down, pause, stand smoothly.",
    scope: "personal",
    ownerName: "Alex Morgan",
    defaultMode: "sets",
    defaultFields: ["reps", "load", "rpe"],
  },
  {
    id: "hill-carry",
    name: "Hill carry",
    category: "General",
    cue: "Walk tall and keep the breathing controlled.",
    scope: "personal",
    ownerName: "Alex Morgan",
    defaultMode: "intervals",
    defaultFields: ["rounds", "duration", "rpe"],
  },
];

const preparation = {
  id: "prepare",
  title: "Preparation",
  items: [
    {
      id: "prep-1",
      title: "5 min easy bike",
      cue: "Raise temperature gradually.",
      mode: "none" as const,
      fields: [],
      prescription: {},
    },
    {
      id: "prep-2",
      title: "Hip and shoulder mobility flow",
      cue: "Move comfortably; nothing needs to be logged.",
      mode: "none" as const,
      fields: [],
      prescription: {},
    },
  ],
};

export const initialProgram: Program = {
  id: "foundation",
  athleteId: "demo-alex",
  versionId: "foundation-draft-v1",
  versionStatus: "draft",
  title: "Foundation",
  description:
    "A balanced three-day plan for strength, aerobic fitness, and movement quality.",
  phase: "Base",
  activeWeek: 3,
  ownerName: "Alex Morgan",
  createdById: "demo-alex",
  createdByName: "Alex Morgan",
  sourceType: "self",
  sourceLabel: "Created by you",
  weeks: Array.from({ length: 6 }, (_, index) => ({
    id: `demo-week-${index + 1}`,
    index: index + 1,
    label: index < 2 ? "Ease in" : index < 5 ? "Build" : "Consolidate",
    workouts: [
      {
        id: `w${index + 1}-full`,
        title: "Full body",
        dayLabel: "Monday",
        durationMinutes: 50,
        sections: [
          preparation,
          {
            id: "main-a",
            title: "Main work",
            items: [
              {
                id: "squat-a",
                exerciseId: "back-squat",
                title: "Back squat",
                cue: "Controlled descent · rest 2–3 min",
                mode: "sets",
                fields: ["reps", "load", "rpe"],
                prescription: { sets: 4, reps: "5", targetRpe: "7–8" },
              },
              {
                id: "press-a",
                exerciseId: "bench-press",
                title: "Bench press",
                cue: "Leave two clean reps in reserve.",
                mode: "sets",
                fields: ["reps", "load", "rpe"],
                prescription: { sets: 3, reps: "8", targetRpe: "7" },
              },
            ],
          },
          {
            id: "finish-a",
            title: "Finish",
            items: [
              {
                id: "walk-a",
                title: "5 min relaxed walk",
                cue: "Let breathing settle.",
                mode: "none",
                fields: [],
                prescription: {},
              },
            ],
          },
        ],
      },
      {
        id: `w${index + 1}-engine`,
        title: "Strength + engine",
        dayLabel: "Thursday",
        durationMinutes: 55,
        sections: [
          preparation,
          {
            id: "main-b",
            title: "Strength",
            items: [
              {
                id: "squat-b",
                exerciseId: "back-squat",
                title: "Back squat",
                cue: "Controlled descent · rest 2–3 min",
                mode: "sets",
                fields: ["reps", "load", "rpe"],
                prescription: { sets: 4, reps: "5", targetRpe: "7–8" },
              },
              {
                id: "push-b",
                exerciseId: "push-up",
                title: "Push-up",
                cue: "Stop before form changes.",
                mode: "sets",
                fields: ["reps", "rpe"],
                prescription: { sets: 3, reps: "10–15", targetRpe: "8" },
              },
            ],
          },
          {
            id: "conditioning-b",
            title: "Conditioning",
            items: [
              {
                id: "bike-b",
                exerciseId: "zone-2-bike",
                title: "Zone 2 bike",
                cue: "Conversational pace.",
                mode: "result",
                fields: ["duration", "distance", "rpe"],
                prescription: { durationMinutes: 20, targetRpe: "5–6" },
              },
            ],
          },
          {
            id: "finish-b",
            title: "Cooldown",
            items: [
              {
                id: "cool-b",
                title: "Easy stretch and breathing",
                cue: "2–5 minutes, no tracking required.",
                mode: "none",
                fields: [],
                prescription: {},
              },
            ],
          },
        ],
      },
      {
        id: `w${index + 1}-cardio`,
        title: "Cardio + core",
        dayLabel: "Weekend",
        durationMinutes: 45,
        sections: [
          {
            id: "run-c",
            title: "Aerobic work",
            items: [
              {
                id: "run-c1",
                exerciseId: "easy-run",
                title: "Easy run",
                cue: "Keep the whole effort conversational.",
                mode: "result",
                fields: ["duration", "distance", "rpe"],
                prescription: { durationMinutes: 30, targetRpe: "5" },
              },
            ],
          },
          {
            id: "core-c",
            title: "Core",
            items: [
              {
                id: "plank-c",
                exerciseId: "plank",
                title: "Plank",
                cue: "Strong position and calm breathing.",
                mode: "result",
                fields: ["duration", "rpe"],
                prescription: { durationMinutes: 1, targetRpe: "7" },
              },
            ],
          },
        ],
      },
    ],
  })),
};

export const completedSessions: CompletedSession[] = [
  {
    id: "s1",
    workoutTitle: "Full body",
    date: "2026-08-03",
    durationMinutes: 48,
    rpe: 7,
  },
  {
    id: "s2",
    workoutTitle: "Strength + engine",
    date: "2026-08-06",
    durationMinutes: 56,
    rpe: 7.5,
  },
  {
    id: "s3",
    workoutTitle: "Cardio + core",
    date: "2026-08-09",
    durationMinutes: 42,
    rpe: 6,
  },
  {
    id: "s4",
    workoutTitle: "Full body",
    date: "2026-08-11",
    durationMinutes: 51,
    rpe: 7.5,
  },
  {
    id: "s5",
    workoutTitle: "Strength + engine",
    date: "2026-08-14",
    durationMinutes: 58,
    rpe: 8,
    note: "Last squat set was challenging but clean.",
  },
  {
    id: "s6",
    workoutTitle: "Full body",
    date: "2026-08-18",
    durationMinutes: 49,
    rpe: 7,
  },
];

export const athleteSummaries: AthleteSummary[] = [
  {
    id: "athlete-1",
    name: "Marta Ozola",
    initials: "MO",
    assignedPrograms: [
      {
        id: "coach-program-1",
        programId: "coach-program-1",
        versionId: "coach-program-version-1",
        title: "Weightlifting base",
        assignedAt: "2026-07-28",
        status: "in_progress",
        totalWorkouts: 12,
        scheduledWorkouts: 12,
        scheduledPercent: 100,
        completedWorkouts: 7,
        completionPercent: 58,
        nextWorkout: {
          id: "coach-workout-1",
          title: "Snatch technique",
          date: "2026-08-24",
        },
      },
    ],
    agenda: [
      {
        id: "coach-schedule-1",
        kind: "upcoming",
        status: "planned",
        programId: "coach-program-1",
        programVersionId: "coach-program-version-1",
        programTitle: "Weightlifting base",
        workoutId: "coach-workout-1",
        workoutTitle: "Snatch technique",
        date: "2026-08-24",
        scheduleId: "coach-schedule-1",
      },
      {
        id: "coach-session-1",
        kind: "completed",
        status: "completed",
        programId: "coach-program-1",
        programVersionId: "coach-program-version-1",
        programTitle: "Weightlifting base",
        workoutId: "coach-workout-2",
        workoutTitle: "Clean & jerk strength",
        date: "2026-08-20",
        rpe: 8,
        sessionId: "coach-session-1",
      },
    ],
  },
  {
    id: "athlete-2",
    name: "Leo Grant",
    initials: "LG",
    assignedPrograms: [
      {
        id: "coach-program-2",
        programId: "coach-program-2",
        versionId: "coach-program-version-2",
        title: "Two-day strength",
        assignedAt: "2026-08-05",
        status: "in_progress",
        totalWorkouts: 8,
        scheduledWorkouts: 5,
        scheduledPercent: 63,
        completedWorkouts: 3,
        completionPercent: 38,
        nextWorkout: {
          id: "coach-workout-3",
          title: "Full body B",
          date: "2026-08-23",
        },
      },
    ],
    agenda: [
      {
        id: "coach-schedule-2",
        kind: "upcoming",
        status: "planned",
        programId: "coach-program-2",
        programVersionId: "coach-program-version-2",
        programTitle: "Two-day strength",
        workoutId: "coach-workout-3",
        workoutTitle: "Full body B",
        date: "2026-08-23",
        scheduleId: "coach-schedule-2",
      },
      {
        id: "coach-session-2",
        kind: "completed",
        status: "completed",
        programId: "coach-program-2",
        programVersionId: "coach-program-version-2",
        programTitle: "Two-day strength",
        workoutId: "coach-workout-4",
        workoutTitle: "Full body A",
        date: "2026-08-19",
        rpe: 9,
        sessionId: "coach-session-2",
      },
    ],
  },
  {
    id: "athlete-3",
    name: "Sara Klein",
    initials: "SK",
    assignedPrograms: [
      {
        id: "coach-program-3",
        programId: "coach-program-3",
        versionId: "coach-program-version-3",
        title: "Return to running",
        assignedAt: "2026-07-01",
        status: "completed",
        totalWorkouts: 6,
        scheduledWorkouts: 6,
        scheduledPercent: 100,
        completedWorkouts: 6,
        completionPercent: 100,
      },
    ],
    agenda: [
      {
        id: "coach-session-3",
        kind: "completed",
        status: "completed",
        programId: "coach-program-3",
        programVersionId: "coach-program-version-3",
        programTitle: "Return to running",
        workoutId: "coach-workout-5",
        workoutTitle: "Easy run + strides",
        date: "2026-08-18",
        rpe: 4,
        sessionId: "coach-session-3",
      },
    ],
  },
];

export const demoProgramTemplates: ProgramTemplate[] = [
  {
    id: "template-strength",
    title: "Flexible Strength",
    description: "Three balanced strength sessions with simple progression.",
    weekCount: 4,
    sessionsPerWeek: 3,
    sourceLabel: "LiftLog library",
  },
  {
    id: "template-bodybuilding",
    title: "Bodybuilding Essentials",
    description: "Two full-body hypertrophy sessions for a busy week.",
    weekCount: 4,
    sessionsPerWeek: 2,
    sourceLabel: "LiftLog library",
  },
  {
    id: "template-cardio",
    title: "Cardio Reset",
    description: "One approachable aerobic session per week.",
    weekCount: 6,
    sessionsPerWeek: 1,
    sourceLabel: "LiftLog library",
  },
];

const today = new Date();
const todayIso = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, "0")}-${String(today.getDate()).padStart(2, "0")}`;
export const demoSchedules: ScheduledWorkout[] = [
  {
    id: "demo-schedule-today",
    programId: initialProgram.id,
    programTitle: initialProgram.title,
    programVersionId: initialProgram.versionId,
    workoutId:
      initialProgram.weeks[initialProgram.activeWeek - 1].workouts[0].id,
    workoutTitle:
      initialProgram.weeks[initialProgram.activeWeek - 1].workouts[0].title,
    slotLabel: "Workout 1",
    plannedDate: todayIso,
    sequenceNumber: 1,
    status: "planned",
    sourceType: initialProgram.sourceType,
    sourceLabel: initialProgram.sourceLabel,
    createdByName: initialProgram.createdByName,
    workout: {
      ...initialProgram.weeks[initialProgram.activeWeek - 1].workouts[0],
      programVersionId: initialProgram.versionId,
      scheduledWorkoutId: "demo-schedule-today",
      plannedDate: todayIso,
    },
  },
];

export const demoWorkspace: WorkspaceData = {
  profile: {
    id: "demo-alex",
    firstName: "Alex",
    lastName: "Morgan",
    displayName: "Alex Morgan",
    liftlogId: "LL-DEMO000100000001",
    weekStartsOnSunday: false,
    weightUnit: "kg",
    distanceUnit: "km",
  },
  programCatalog: [initialProgram],
  schedulableProgramIds: [initialProgram.id],
  schedulablePrograms: [initialProgram],
  draftProgram: initialProgram,
  activeProgram: initialProgram,
  scheduledWorkouts: demoSchedules,
  globalExercises,
  personalExercises: initialPersonalExercises,
  completedSessions,
  coachConnections: [
    {
      relationshipId: "demo-relationship",
      coachId: "demo-coach",
      name: "Nina Kovacs",
      initials: "NK",
      connectedSince: "2026-07-12",
    },
  ],
  coachedAthletes: athleteSummaries,
  pendingCoachInvites: [],
  outgoingCoachInvites: [],
  activeSession: null,
};
